In [1]:
import pandas as pd

In [35]:
import matplotlib.pyplot as plt 
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [2]:
df = pd.read_csv("master_combined.csv")

In [3]:
df

,Unnamed: 0,cidade,longitude,latitude,periodo_inicial,periodo_final,ndvi_medio,evi_medio,leaf_area_index_medio,sm_rootzone_pctl_medio,sm_profile_pctl_medio,lst_day_1km_c
0,0,citrus,-48.739073,-22.898479,2020-01-01,2020-01-21,0.7368,0.5749,2.302981,26.348715,22.826978,30.452304
1,1,citrus,-48.739073,-22.898479,2020-01-21,2020-02-10,0.7358,0.5356,2.504077,30.565119,21.904745,29.846498
2,2,citrus,-48.739073,-22.898479,2020-02-10,2020-03-01,0.7669,0.5372,2.537258,51.711988,47.832835,28.016704
3,3,citrus,-48.739073,-22.898479,2020-03-01,2020-03-21,0.7603,0.4648,2.482293,41.970760,42.694477,29.162826
4,4,citrus,-48.739073,-22.898479,2020-03-21,2020-04-10,0.7485,0.4572,2.363566,NaN,20.360136,27.481180
...,...,...,...,...,...,...,...,...,...,...,...,...
1559,87,Café,-48.600133,-22.613829,2024-10-06,2024-10-26,0.3673,0.2295,1.262413,8.697375,2.231184,35.069089
1560,88,Café,-48.600133,-22.613829,2024-10-26,2024-11-15,0.4480,0.2226,1.501185,49.126358,27.664883,34.838903
1561,89,Café,-48.600133,-22.613829,2024-11-15,2024-12-05,0.5273,0.3632,1.798305,34.459446,34.716396,36.728764
1562,90,Café,-48.600133,-22.613829,2024-12-05,2024-12-25,0.6326,0.3918,2.393952,38.534442,47.597971,30.135879
1563,91,Café,-48.600133,-22.613829,2024-12-25,2025-01-14,0.6612,0.4299,3.059018,24.489710,33.158230,30.606712

In [4]:
new_df = df.drop(columns=['Unnamed: 0'])

In [5]:
new_df

,cidade,longitude,latitude,periodo_inicial,periodo_final,ndvi_medio,evi_medio,leaf_area_index_medio,sm_rootzone_pctl_medio,sm_profile_pctl_medio,lst_day_1km_c
0,citrus,-48.739073,-22.898479,2020-01-01,2020-01-21,0.7368,0.5749,2.302981,26.348715,22.826978,30.452304
1,citrus,-48.739073,-22.898479,2020-01-21,2020-02-10,0.7358,0.5356,2.504077,30.565119,21.904745,29.846498
2,citrus,-48.739073,-22.898479,2020-02-10,2020-03-01,0.7669,0.5372,2.537258,51.711988,47.832835,28.016704
3,citrus,-48.739073,-22.898479,2020-03-01,2020-03-21,0.7603,0.4648,2.482293,41.970760,42.694477,29.162826
4,citrus,-48.739073,-22.898479,2020-03-21,2020-04-10,0.7485,0.4572,2.363566,NaN,20.360136,27.481180
...,...,...,...,...,...,...,...,...,...,...,...
1559,Café,-48.600133,-22.613829,2024-10-06,2024-10-26,0.3673,0.2295,1.262413,8.697375,2.231184,35.069089
1560,Café,-48.600133,-22.613829,2024-10-26,2024-11-15,0.4480,0.2226,1.501185,49.126358,27.664883,34.838903
1561,Café,-48.600133,-22.613829,2024-11-15,2024-12-05,0.5273,0.3632,1.798305,34.459446,34.716396,36.728764
1562,Café,-48.600133,-22.613829,2024-12-05,2024-12-25,0.6326,0.3918,2.393952,38.534442,47.597971,30.135879
1563,Café,-48.600133,-22.613829,2024-12-25,2025-01-14,0.6612,0.4299,3.059018,24.489710,33.158230,30.606712

In [6]:
new_df['periodo_inicial'] = pd.to_datetime(new_df['periodo_inicial'])

In [7]:
new_df['periodo_final'] = pd.to_datetime(new_df['periodo_final'])

In [8]:
new_df['month'] = new_df['periodo_inicial'].dt.month

In [9]:
new_df['year'] = new_df['periodo_inicial'].dt.year

In [10]:
def apply_season(number):
    if(number) in (12,1,2):
        return 'verao'
    elif(number) in (3,4,5):
        return 'outono'
    elif(number) in (6,7,8):
        return 'inverno'
    elif (number) in (9,10,11):
        return 'primavera'

In [11]:
new_df['season'] = new_df['month'].apply(apply_season)

In [12]:
new_df

,cidade,longitude,latitude,periodo_inicial,periodo_final,ndvi_medio,evi_medio,leaf_area_index_medio,sm_rootzone_pctl_medio,sm_profile_pctl_medio,lst_day_1km_c,month,year,season
0,citrus,-48.739073,-22.898479,2020-01-01,2020-01-21,0.7368,0.5749,2.302981,26.348715,22.826978,30.452304,1,2020,verao
1,citrus,-48.739073,-22.898479,2020-01-21,2020-02-10,0.7358,0.5356,2.504077,30.565119,21.904745,29.846498,1,2020,verao
2,citrus,-48.739073,-22.898479,2020-02-10,2020-03-01,0.7669,0.5372,2.537258,51.711988,47.832835,28.016704,2,2020,verao
3,citrus,-48.739073,-22.898479,2020-03-01,2020-03-21,0.7603,0.4648,2.482293,41.970760,42.694477,29.162826,3,2020,outono
4,citrus,-48.739073,-22.898479,2020-03-21,2020-04-10,0.7485,0.4572,2.363566,NaN,20.360136,27.481180,3,2020,outono
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1559,Café,-48.600133,-22.613829,2024-10-06,2024-10-26,0.3673,0.2295,1.262413,8.697375,2.231184,35.069089,10,2024,primavera
1560,Café,-48.600133,-22.613829,2024-10-26,2024-11-15,0.4480,0.2226,1.501185,49.126358,27.664883,34.838903,10,2024,primavera
1561,Café,-48.600133,-22.613829,2024-11-15,2024-12-05,0.5273,0.3632,1.798305,34.459446,34.716396,36.728764,11,2024,primavera
1562,Café,-48.600133,-22.613829,2024-12-05,2024-12-25,0.6326,0.3918,2.393952,38.534442,47.597971,30.135879,12,2024,verao
1563,Café,-48.600133,-22.613829,2024-12-25,2025-01-14,0.6612,0.4299,3.059018,24.489710,33.158230,30.606712,12,2024,verao

In [13]:
new_df = new_df.groupby(["cidade", "latitude","longitude", "season"]).agg({
    "ndvi_medio": "mean",
    "evi_medio": "mean",
    "leaf_area_index_medio": "mean",
    "sm_rootzone_pctl_medio": "mean",
    "sm_profile_pctl_medio": "mean",
    "lst_day_1km_c": "mean"
}).reset_index()

In [14]:
new_df

,cidade,latitude,longitude,season,ndvi_medio,evi_medio,leaf_area_index_medio,sm_rootzone_pctl_medio,sm_profile_pctl_medio,lst_day_1km_c
0,Café,-22.613829,-48.600133,inverno,0.470070,0.275778,1.251994,24.824062,24.039805,26.965720
1,Café,-22.613829,-48.600133,outono,0.679887,0.461735,2.877530,25.607332,26.180549,26.511474
2,Café,-22.613829,-48.600133,primavera,0.457177,0.270950,1.426642,30.293574,25.042934,36.355218
3,Café,-22.613829,-48.600133,verao,0.692833,0.487683,3.383221,32.755560,29.886388,31.672164
4,abacate,-23.192666,-48.887991,inverno,0.599770,0.336430,1.316448,19.911285,18.091132,24.504879
...,...,...,...,...,...,...,...,...,...,...
63,eucalipto,-22.806760,-48.373961,verao,0.796679,0.557037,2.516928,36.512563,25.730972,28.633644
64,eucalipto,-22.496249,-48.519240,inverno,0.510370,0.281174,1.098557,24.479193,22.445456,24.702388
65,eucalipto,-22.496249,-48.519240,outono,0.712474,0.477596,2.492335,20.616566,25.770940,25.405147
66,eucalipto,-22.496249,-48.519240,primavera,0.462227,0.276741,0.969997,27.675692,24.039435,33.735487
67,eucalipto,-22.496249,-48.519240,verao,0.673521,0.472129,2.567680,35.475744,28.137101,31.351172

In [15]:
new_df['cidade'] = new_df['cidade'].str.lower()

In [28]:
new_df[
    (new_df['cidade'] == 'café') &
    (new_df['latitude'].round(6) == -22.613829) &
    (new_df['longitude'].round(6) == -48.600133)
]

,cidade,latitude,longitude,season,ndvi_medio,evi_medio,leaf_area_index_medio,sm_rootzone_pctl_medio,sm_profile_pctl_medio,lst_day_1km_c
0,café,-22.613829,-48.600133,inverno,0.470070,0.275778,1.251994,24.824062,24.039805,26.965720
1,café,-22.613829,-48.600133,outono,0.679887,0.461735,2.877530,25.607332,26.180549,26.511474
2,café,-22.613829,-48.600133,primavera,0.457177,0.270950,1.426642,30.293574,25.042934,36.355218
3,café,-22.613829,-48.600133,verao,0.692833,0.487683,3.383221,32.755560,29.886388,31.672164

In [29]:
new_df.describe()

,latitude,longitude,ndvi_medio,evi_medio,leaf_area_index_medio,sm_rootzone_pctl_medio,sm_profile_pctl_medio,lst_day_1km_c
count,68.000000,68.000000,68.000000,68.000000,68.000000,59.000000,68.000000,68.000000
mean,-22.952899,-48.547120,0.673527,0.428014,1.866575,28.286746,25.872805,27.235883
std,0.254229,0.242056,0.091032,0.079694,0.600983,6.296643,4.172775,3.241088
min,-23.408251,-48.912728,0.457177,0.270950,0.917189,17.221135,16.787031,21.610308
25%,-23.117503,-48.741323,0.615605,0.371692,1.348267,23.665957,23.544705,24.653011
50%,-22.908818,-48.564946,0.688970,0.431313,1.789101,27.715182,25.372341,26.936420
75%,-22.806760,-48.373961,0.736925,0.484638,2.315689,32.788715,29.235227,29.641019
max,-22.496249,-48.063649,0.850570,0.572400,3.383221,46.609841,34.978664,36.355218

In [31]:
df_corr = new_df.corr